### PR TITLE
Fix #700. Add option to ignore broken symlinks in directories

### LINKED ISSUE #700: Add option to ignore broken symlinks in directories
When using the "directory" src type, the plugin fails with the following error when it encounters a broken symlink:
`Caused by: java.io.FileNotFoundException: <filepath> (No such file or directory)
`
Most other maven plugins (for example the rpm-maven-plugin and maven-assembly-plugin) ignore any broken symlinks and process the rest of the directory.

When building large projects with lots of dependencies, there is a change one of them has a broken symlink somewhere, so plugins should be able to deal with it (by ignoring the broken symlink), or at least have an option to do that.

I can workaround the issue by first packaging the stuff I want into a tgz (using maven-assembly-plugin) and then using that as the src for jdeb, but jdeb should exhibit a behavior that's consistent with other maven plugins.

I've also attached my plugin configuration (project-specific and company-specific identifiers removed)
[jdeb.txt](https://github.com/user-attachments/files/15928821/jdeb.txt)

### PR DESCRIPTION
**Pull request by marwiik**
Here's my suggested solution. I'm open for suggestions if there's a better way to pass along the ignoreBrokenLinks parameter, or any other improvements.

### CODE REVIEW

**Comment by tcurdt** [comment]
Thanks for the contribution! And also providing docs and test cases!
Looking OK on a quick glance. We just need to double check if this changes any of the external interfaces.

**Comment by marwiik** [comment]
Sounds good. Not changing the default behaviour was one of the main considerations for my solution. But to make sure, I could add a second buildData method with the old signature which just calls the new one with the default "false" new parameter. Just in case someone is using the DataBuilder api outside of maven. Is that what you had in mind, or have I overlooked something?

Also, I just realised I forgot to add the new parameter in the doc comment. I'll fix that first.

File: src/main/java/org/vafer/jdeb/DataBuilder.java [hunk 1]
```diff
@@ -278,6 +282,15 @@ private void createParentDirectories( String filename, String user, long uid, St
             for (DataProducer data : producers) {
                 data.produce(receiver);
             }
+        } catch (FileNotFoundException e) {
+            String[] arr = e.getMessage().split(" ");
```
Comment (tcurdt) [inline src/main/java/org/vafer/jdeb/DataBuilder.java:286]: This look too brittle. The very least we would need some comments on way this should work.

File: src/main/java/org/vafer/jdeb/DebMaker.java [hunk 2]
```diff
@@ -487,7 +494,7 @@ public BinaryPackageControlFile createSignedDeb(Compression compression, final P
                 .compression(compression)
                 .longFileMode(tarLongFileMode)
                 .bigNumberMode(tarBigNumberMode);
-            BigInteger size = dataBuilder.buildData(dataProducers, tempData, md5s, options);
+            BigInteger size = dataBuilder.buildData(dataProducers, tempData, md5s, options, ignoreBrokenLinks);
```
Comment (tcurdt) [inline src/main/java/org/vafer/jdeb/DebMaker.java:497]: To check: Is `buildData` public API or not?

File: src/main/java/org/vafer/jdeb/DataBuilder.java (hunk 1 above)
Comment (tcurdt) [reply src/main/java/org/vafer/jdeb/DataBuilder.java:288]: AFAIK the only reliable way is to either have a custom exception that wraps the FNF (major fail), or provide the path externally.

I think in this case the only feasible option would be a custom exception that provides the path.
But again we would need to see if this requires changing any signatures. But maybe we just need to catch and re-throw in the producers.

File: src/main/java/org/vafer/jdeb/DebMaker.java (hunk 2 above)
Comment (marwiik) [reply src/main/java/org/vafer/jdeb/DebMaker.java:497]: Upon closer inspection, DataBuilder is package-private, so I guess buildData is not considered a public API.

File: src/main/java/org/vafer/jdeb/DataBuilder.java (hunk 1 above)
Comment (marwiik) [reply src/main/java/org/vafer/jdeb/DataBuilder.java]: I pushed a fix with a custom exception, for which we have control of the exception message. Looks a bit cleaner and more robust to me at least.

File: src/main/java/org/vafer/jdeb/ProducerFileNotFoundException.java [hunk 3]
```diff
@@ -0,0 +1,18 @@
+package org.vafer.jdeb;
+
+import java.io.IOException;
+
+public class ProducerFileNotFoundException extends IOException {
+
```
Comment (tcurdt) [inline src/main/java/org/vafer/jdeb/ProducerFileNotFoundException.java:6]: Why not add an explicit private variable that holds the path?
Nicer than abusing the message.

Should it extend IOException or FileNotFound?

File: src/main/java/org/vafer/jdeb/DataBuilder.java (hunk 1 above)
Comment (tcurdt) [reply src/main/java/org/vafer/jdeb/DataBuilder.java]: Much better. But I think I would avoid re-using the message variable - and then we should be golden.

Comment (marwiik) [reply src/main/java/org/vafer/jdeb/DataBuilder.java]: Done

File: src/main/java/org/vafer/jdeb/ProducerFileNotFoundException.java (hunk 3 above)
Comment (marwiik) [reply src/main/java/org/vafer/jdeb/ProducerFileNotFoundException.java]: I chose IOException at first because FileNotFoundException does not have a constructor that accepts a Throwable as cause. But then I realised I can set the cause manually with initCause, so I switched to extending FileNotFoundException which makes more sense.

**Comment by tcurdt** [comment]
Thanks a lot!
Can you rebase it so I can merge it?

**Comment by tcurdt** [comment]
Awesome! Thanks for the contribution.

**Comment by marwiik** [comment]
No problem! Thanks for your constructive feedback, I enjoyed it. There's always more to learn.
